##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    - clang-tools
    - cppcheck
    - gettext
    - git
    - gtk-doc-tools
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgnutls28-dev
    - libpango1.0-dev
    - libpcre2-dev
    - libsystemd-dev
    - libxml2-utils
    - meson
    - wget

    #packages required for ctk
    - adwaita-icon-theme
    - dconf-gsettings-backend
    - hicolor-icon-theme
    - libatk-bridge2.0-dev
    - libatk-bridge2.0-0
    - libcolord2
    - libcups2
    - libegl1-mesa-dev
    - libepoxy0
    - libepoxy-dev
    - libfontconfig1-dev
    - libfribidi-dev
    - libgdk-pixbuf2.0-dev
    - libjson-glib-1.0-0
    - libpango1.0-dev
    - librest-0.7-0
    - libwayland-dev
    - libx11-dev
    - libxcomposite-dev
    - libxcursor-dev
    - libxdamage-dev
    - libxext-dev
    - libxfixes-dev
    - libxi-dev
    - libxinerama-dev
    - libxkbcommon-dev
    - libxrandr-dev
    - wayland-protocols

variables:
  - CXXFLAGS="-Wall -Woverloaded-virtual -Wextra -Wshadow -Wformat-nonliteral -Werror=format-security -Wpointer-arith -Wcast-align -Wmissing-declarations -Wredundant-decls -Wall -Wcast-align -Wextra -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wpointer-arith -Wredundant-decls -Wshadow -Werror=format-security -Wunused-macros"
  - CFLAGS="-Wall -Wextra -Wshadow -Wformat-nonliteral -Werror=format-security -Wpointer-arith -Wcast-align -Wmissing-declarations -Wredundant-decls -Wall -Wmissing-prototypes -Wbad-function-cast -Wcast-align -Wextra -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Werror=format-security -Wunused-macros"

before_scripts:
  - export TITLECPPCHECK="${REPO_NAME} (cppcheck `dpkg -s cppcheck|grep -i version|cut -d " " -f 2`)"
  - cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude .
  - cppcheck-htmlreport --title="$TITLECPPCHECK" --file=cppcheck.xml --report-dir=cppcheck-htmlreport

  # Install required ctk .deb packages
  - git clone https://github.com/cafe-desktop/ctk.git -b master ctk-master
  - cd ctk-master
  - wget https://github.com/cafe-desktop/ctk/releases/download/`git describe --abbrev=0 --tags`/libctk-3-dev_`git describe --abbrev=0 --tags|sed 's/^.//'`-1_amd64.deb
  - wget https://github.com/cafe-desktop/ctk/releases/download/`git describe --abbrev=0 --tags`/gir1.2-ctk-3.0_`git describe --abbrev=0 --tags|sed 's/^.//'`-1_amd64.deb
  - wget https://github.com/cafe-desktop/ctk/releases/download/`git describe --abbrev=0 --tags`/libctk-3-common_`git describe --abbrev=0 --tags|sed 's/^.//'`-1_all.deb
  - wget https://github.com/cafe-desktop/ctk/releases/download/`git describe --abbrev=0 --tags`/libctk-3-0_`git describe --abbrev=0 --tags|sed 's/^.//'`-1_amd64.deb
  - dpkg -i *.deb
  - cd ..
  - rm -rf ctk-master

build_scripts:
  - export TITLESCANBUILD="${REPO_NAME} (clang-tools `dpkg -s clang-tools|grep -i version|cut -d " " -f 2`) - scan-build results"
  - mkdir html-report
  - cppcheck --enable=warning,style,performance,portability,information,missingInclude . 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - scan-build $CHECKERS --keep-cc meson _build 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - scan-build $CHECKERS --keep-cc -o html-report --html-title="$TITLESCANBUILD" ninja -C _build 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - apt list --installed libctk-3-dev 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - echo Warnings detected in the logs `cat ./html-report/output_${TRAVIS_COMMIT} | grep -i warning | wc -l` 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}

after_scripts:
  - ./gen-index -l 20
